# SonarQube Configuration for Frontend
sonar.projectKey=frontend-currency-converter
sonar.host.url=https://sonar.techwithrushi.online
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/*.test.js
