# SonarQube Configuration for Backend
sonar.projectKey=backend-currency-converter
sonar.host.url=https://sonar.techwithrushi.online
sonar.sources=src/main/java
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
