spring.datasource.driver=org.postgresql.Driver
#server.port=8005

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

security.jwt.secret-key=${JWT_SECRET_KEY}
# 1h in millisecond
security.jwt.expiration-time=3600000
server.servlet.context-path=/api
exchange.rate.api.url=${EX_API}
cors.url=${CORS_URL}
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
# Enable metrics using micometer
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.defaults.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true


