
#Test CI workflow
name: "Test CI Workflow"

on: 
 push:
 pull_request: 
  branches: [main]

jobs: 
 build:
   runs-on: ubuntu-latest
   
   steps:
     - name: code checkout
       uses: actions/checkout@v4

     - name: List files
       run: ls -la
